apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-orderdb
spec:
  selector:
    matchLabels:
      app: mysql-orderdb
  template:
    metadata:
      labels:
        app: mysql-orderdb
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: orderdb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-orderdb-pvc
      - name: initdb
        configMap:
          name: orderdb-initdb