name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 734842486567.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t 734842486567.dkr.ecr.us-east-2.amazonaws.com/cmm707/node-order-service:latest .
          docker push 734842486567.dkr.ecr.us-east-2.amazonaws.com/cmm707/node-order-service:latest

      - name: Update kubeconfig
        run:  aws eks --region us-east-2 update-kubeconfig --name lugx-gaming

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/mysql-pvc.yaml
          kubectl apply -f k8s/mysql-configmap.yaml
          kubectl apply -f k8s/mysql-service.yaml
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/order-service.yaml
          kubectl apply -f k8s/order-deployment.yaml